version: '3'

services:
  mongo:
    image: mongo:3.4.19-jessie
    container_name: ca-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    logging:
      driver: none
  idxMongo:
    image: mongo:3.4.19-jessie
    container_name: ca-idx
    logging:
      driver: none
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    build: "./Deps/Bindaas/"
    depends_on:
      - "mongo"
    container_name: ca-data
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git#v3.2.0"
    container_name: ca-iip
    restart: unless-stopped
    volumes:
      - ./images/:/images/
  viewer:
    build: "./caMicroscope"
    container_name: ca-front
    restart: unless-stopped
    volumes:
      - ./caMicroscope:/var/www/html/
    logging:
      driver: none
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git#v3.2.0"
    container_name: ca-load
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - ./images/:/images/
  security:
    build: "https://github.com/camicroscope/Security.git#v3.2.2"
    container_name: ca-security
    restart: unless-stopped
    ports:
      - "4010:4010"
    volumes:
      - ./config/routes.json:/root/src/routes.json
      - ./jwt_keys/:/keys/
    environment:
      - DISABLE_SEC=true
  auth:
    build: "./Deps/auth_service/"
    volumes:
      - ./jwt_keys/:/keys/
    container_name: ca-auth
    restart: unless-stopped
    logging:
      driver: none
